//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Place4meModels;

    [MetadataType(typeof(SlotDetails))]
    public partial class slot_details
    {
        public int slot_details_id { get; set; }
        public string slot_details_parked_time { get; set; }
        public string slot_details_parked_end_time { get; set; }
        public System.DateTime slot_details_parked_date { get; set; }
        public string slot_details_parked_vehicle_no { get; set; }
        public int slot_details_status { get; set; }
        public int slot_id { get; set; }
    
        public virtual slot slot { get; set; }
    }
}
